[package]
name = "li2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.crypto]
version = "0.4.0"
features = ["signature"]